<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- - - - - - -->
    <!-- Variables -->
    <!-- - - - - - -->
    <xacro:property name="chassis_length" value="0.3" />
    <xacro:property name="chassis_width" value="0.18" />
    <xacro:property name="chassis_height" value="0.11" />
    <xacro:property name="rear_axel_position" value="${chassis_length / -3.5}" />
    <xacro:property name="wheel_length" value="0.04" />
    <xacro:property name="wheel_radius" value="0.058" />
    <xacro:property name="shpere_radius" value="0.03" />


    <!-- - - - - - - - - - - -->
    <!-- Macros or Functions -->
    <!-- - - - - - - - - - - -->
    <xacro:macro name="create_new_wheel" params="prefix is_left" >
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="-${pi / 2} 0 0" />
                <material name="black" />
            </visual>

            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="-${pi / 2} 0 0" />
            
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="-${pi / 2} 0 0" />
            </collision>
        </link>
        <joint name="base_${prefix}_wheel_joint" type="continuous">
            <parent link="chassis_link" />
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${rear_axel_position} ${0.11 * is_left} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- - -  -->
    <!-- Base -->
    <!-- - -  -->
    <link name="base_link">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>
    
    <!-- - - - - -->
    <!-- Chassis -->
    <!-- - - - - -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <xacro:box_inertia m="1.5" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}" xyz="0 0 0.05" rpy="0 0 0"/>

        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 0.059" rpy="0 0 0"/>
        </collision>
    </link>
    <joint name="foot_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_link"/>
        <origin xyz="0 0 0.055" rpy="0 0 0" />
    </joint>

    <!-- - - - - -  -->
    <!-- - Caster - -->
    <!-- - - - - -  -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${shpere_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>

        <xacro:shpere_inertia m="0.15" r="${shpere_radius}" xyz="0 0 0.05" rpy="0 0 0"/>

        <collision>
            <geometry>
                <sphere radius="${shpere_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
    </link>
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="caster_wheel_link"/>
        <origin xyz=".1 0 -.029" rpy="0 0 0" />
    </joint>

    <!-- - - - - - -  -->
    <!-- Drive Wheels -->
    <!-- - - - - - -  -->
    <xacro:create_new_wheel prefix="right" is_left="1" />
    <xacro:create_new_wheel prefix="left" is_left="-1" />

    <!-- - -  -->
    <!-- Mesh -->
    <!-- - -  -->
    <!-- <link name="sonar_link">
        <visual>
            <geometry>
                <mesh filename="package://optimus_v1_description/meshes/dual_sonar_v1.0.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 ${pi /2}" />
            <material name="black" />
        </visual>
    </link>
    <joint name="chassis_sonar_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="sonar_link"/>
        <origin xyz="${chassis_length / 2 - 0.015} 0 ${(-chassis_height / 4) + 0.005}" rpy="0 0 0" />
    </joint> -->

</robot>